name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Show all files and folder
      run : ls HelloWorld
    - name: Build the Docker image
      run: docker build . --file ../Dockerfile --tag mesbaulhasan/helloworld:latest
